	<div id="footer-wrapper" class="container-fluid">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<div class="row">
						<div class="col-lg-4 col-md-6 col-sm-5 col-xs-5"><p>Dash with us:</p></div>
						<div class="col-md-1 col-sm-1 col-xs-1 no-margin">
							<a href="#" onclick="window.open('http://www.facebook.com/sharer.php?u=http%3A%2F%2Fwww.dash.com.sg%2Findex.html','sharer','toolbar=0,status=0,width=548,height=325'); return false;" class="facebook"></a>
						</div>
						<div class="col-md-1 col-sm-1 col-xs-1">
							<a href="#" onclick="window.open('https://twitter.com/share?url=http%3A%2F%2Fwww.dash.com.sg%2Findex.html&amp;text=We%27re+Dash.+We%E2%80%99ve+updated+money+and+you+can+now+download+cash+into+your+phone%21','sharer','toolbar=0,status=0,width=548,height=325'); return false;" class="twitter"></a>
						</div>
					
					</div>
				</div>
				<div class="col-md-2 col-sm-12 col-xs-12 col-md-offset-1">
					<ul>
						<li><a href="who-we-are.shtml">Who We Are</a></li>
						<li><a href="save-money.shtml">Dash Easy</a></li>
						<li><a href="dash-advance.shtml">Dash Advanced</a></li>
						<li><a href="dash-abroad.shtml">Dash Abroad</a></li>
						<!-- <li><a href="#login-alert" class="login">Dash Banking</a></li> -->
						<!-- <li><a href="make-it-right.shtml">Make It Right</a></li> -->
						
					</ul>
				</div>
				<div class="col-md-2 col-sm-12 col-xs-12">
					<ul>
						<li><a href="http://www.dash.com.sg/dash-partner-solutions.html">Dash Partner Solutions</a></li>
						<li><a href="make-it-right.shtml">Security</a></li>
						<li><a href="terms.shtml">Terms & Conditions</a></li>
			 			<!-- <li><a href="http://www.dash.com.sg/assets/pdf/privacy-policy.pdf" target="_blank">Data Protection</a></li> -->			 			
					</ul>
				</div>
				<div class="col-md-2 col-sm-12 col-xs-12 col-md-offset-1">
					<ul>
						<li><a href="https://contact.dash.com.sg/">Contact us</a></li>
						<!-- <li><span class="other">Other Dash Products:</span></li>
						<li><a href="dash-advance.shtml">Dash Advance</a></li>
						<li><a href="dash-abroad.shtml">Dash Abroad</a></li> -->
					</ul>
				</div>
				
				<!-- <div class="col-md-2">
					<div class="search">
						<form action="search.shtml" method="post">
							<input type="text" class="search searchInput" placeholder="Search">
							<button class="searchBtn"></button>
						</form>
					</div>
				</div> -->
			</div>
		</div>

	</div>
	<div id="copyright-wrapper" class="container-fluid">
		<p>&copy; 2014 Dash. Created by Singtel and Standard Chartered. All rights reserved.</p>
	</div>
	<div style="display:none">
		<div id="login-alert">
			<h5>Login to Dash Banking</h5>
			<p>You will now be directed to the internet banking platform of Standard Chartered Bank (Singapore) Limited.</p>

			<p class="cta-btn-2 t33"><a href="https://ibank.standardchartered.com.sg/nfs/login.htm?channelcode=ST">Proceed</a></p>
		</div>
	</div>
</div><!-- page wrapper end -->