	<div id="footer-wrapper" class="container-fluid">
		<div class="container">
			<div class="row">
				<div class="col-md-2">
					<p>Dash with us:</p><a href="#" onclick="window.open('http://www.facebook.com/sharer.php?u=http%3A%2F%2Fwww.dash.com.sg%2Findex.html','sharer','toolbar=0,status=0,width=548,height=325'); return false;" class="facebook"></a><a href="#" onclick="window.open('https://twitter.com/share?url=http%3A%2F%2Fwww.dash.com.sg%2Findex.html&amp;text=We%27re+Dash.+We%E2%80%99ve+updated+money+and+you+can+now+download+cash+into+your+phone%21','sharer','toolbar=0,status=0,width=548,height=325'); return false;" class="twitter"></a>
				</div>
				<div class="col-md-2 col-md-offset-2">
					<ul>
						<li><a href="dash-advance.shtml">Dash Advance</a></li>
						<li><a href="who-we-are.shtml">Who We Are</a></li>
					</ul>
				</div>
				<div class="col-md-2">
					<ul>
						<li><a href="dash-abroad.shtml">Dash Abroad</a></li>
						<li><a href="terms.shtml">Terms</a></li>
					</ul>
				</div>
				<div class="col-md-2">
					<ul>
						<li><a href="make-it-right.shtml">Make it Right</a></li>
					</ul>
				</div>
				<!-- <div class="col-md-2">
					<div class="search">
						<form action="search.shtml" method="post">
							<input type="text" class="search searchInput" placeholder="Search">
							<button class="searchBtn"></button>
						</form>
					</div>
				</div> -->
			</div>
		</div>

	</div>
	<div id="copyright-wrapper" class="container-fluid">
		<p>&copy; 2014 Dash. Created by SingTel and Standard Chartered. All rights reserved.</p>
	</div>
</div><!-- page wrapper end -->