	<div id="footer-wrapper" class="container-fluid">
		<div class="container">
			<div class="row">
				<div class="col-md-2">
					<p>Dash with us:</p><a href="" class="facebook"></a><a href="" class="twitter"></a>
				</div>
				<div class="col-md-2">
					<ul>
						<li><a href="#">Dash Advance</a></li>
						<li><a href="#" class="long">Product Selector Form</a></li>
					</ul>
				</div>
				<div class="col-md-2">
					<ul>
						<li><a href="#">Dash Abroad</a></li>
						<li><a href="#">Prime Form</a></li>
					</ul>
				</div>
				<div class="col-md-2">
					<ul>
						<li><a href="#">Make it Right</a></li>
						<li><a href="#">Preform</a></li>
					</ul>
				</div>
				<div class="col-md-2">
					<ul>
						<li><a href="#">Who We Are</a></li>
						<li><a href="#">Terms</a></li>
					</ul>
				</div>
				<div class="col-md-2">
					<div class="search">
						<input type="text" class="search searchInput" placeholder="Search">
						<button class="searchBtn"></button>
					</div>
				</div>
			</div>
		</div>

	</div>
	<div id="copyright-wrapper" class="container-fluid">
		<p>&copy; 2014 Dash. Created by SingTel and Standard Chartered. All rights reserved.</p>
	</div>
</div><!-- page wrapper end -->