<div id="page-wrapper">
	<div id="header-wrapper" class="container-fluid">
		<header id="main-header" class="container">
			<div class="row">
				<div class="col-md-2">
					<a href="home.shtml"><img src="images/logo/main-logo.png" alt="dash logo"></a>
				</div>
				<div class="col-md-6 col-md-offset-1">
					<div id="menu-wrapper">
						<nav>
							<ul class="main-menu">
								<li><a href="#">Pay Business</a></li>
								<li><a href="#">Pay Friends</a></li>
								<li><a href="#">Dash Easy</a></li>
								<li><a href="#">FAQS</a></li>
								<li><a href="#">Contact us</a></li>
							</ul>
						</nav>
					</div>		
				</div>
				<div class="col-md-3">
					<a href="#" class="cta-btn login">LOG IN</a>
					<a href="#" class="cta-btn apply">APPLY NOW</a>
				</div>
			</div>
		</header>
	</div>
