<div id="page-wrapper">
	<div id="header-wrapper" class="container-fluid">
		<header id="main-header" class="container">
			<div class="row">
				<div class="col-md-9 col-sm-12 col-xs-12">
					<a href="index.shtml" class="site-logo"><img src="images/logo/main-logo.png" alt="dash logo"></a>

					<div id="menu-wrapper">
						<nav id="nav-main">
							<ul class="main-menu">
								<li><a href="index.shtml">Home</a></li>
								<li>
									<a href="#">Features</a>
									<ul class="sub-menu">
										<li><a href="pay-friends.shtml">Pay Friends</a></li>
										<li><a href="pay-business.shtml">Pay Businesses</a></li>
										<li><a href="save-money.shtml">Save Money</a></li>
										<li><a href="http://www.dash.com.sg/promo.html">Get Deals</a></li>
									</ul>
								</li>
								<li><a href="http://faq.dash.com.sg/">FAQS</a></li>
								<li class="hidden-xs hidden-sm">
									<a href="#">Other products</a>
									<ul class="sub-menu">
										<li><a href="dash-advance.shtml">Dash Advance Personal Loan</a></li>
										<li><a href="dash-abroad.shtml">Dash Abroad Travel Insurance</a></li>
									</ul>
								</li>
							</ul>
						</nav>
						<div id="nav-trigger">
						    <span><div class="box-shadow-menu"></div></span>
						</div>
					</div>		
				</div>
				<div class="col-sm-12 col-xs-12 visible-xs visible-sm">
					<nav id="nav-mobile"></nav>
				</div>
				<div class="col-md-3 col-sm-12 col-xs-12 header-buttons hidden-xs hidden-sm">
					<div class="btn-menu">
						<a href="https://my-mcash.dash.com.sg/index/login" class="cta-btn login">LOG IN</a>
						<ul class="sub-menu">
							<li><a href="#">Login to mCash</a></li>
							<li><a href="#">Login to eBanking</a></li>
						</ul>
					</div>
					<a href="https://apply.dash.com.sg/advance/" target="_blank" class="cta-btn-3 apply">APPLY NOW</a>
				</div>
			</div>
		</header>
	</div>
