<div id="slider-wrapper">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner">
			<div class="item slide-1 active">
			  <!-- <img src="images/content/slider-1.png" alt="slider 1"> -->
			  <div class="img"></div>
			  <div class="carousel-caption">
					<h1>WHAT IS DASH?</h1>
					<h3>A mobile wallet not only saves you the hassle of carrying “real” money but also makes everyday transactions a breeze – and that’s what Dash is about!</h3>

					<p>Download Dash now and get $5 free instantly.</p>

					<button class="cta-btn apply-now">APPLY NOW</button>
			  </div>
			</div>
			<div class="item slide-2">
				<div class="img"></div>
			 <!--  <div class="carousel-caption">
			  		<h1>SHOP WITH DASH</h1>
					<h3>For the first time ever, you no longer have to fumble around for your cash or card when paying at your favourite retail stores and eateries. Simply whip out your smartphone and fire up your Dash app to make an instant and secure payment!</h3>

					<button class="cta-btn apply-now">APPLY NOW</button>
			  </div> -->
			</div>
		</div>
	</div>
</div>