<div id="slider-wrapper">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<!-- <ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			<li data-target="#carousel-example-generic" data-slide-to="3"></li>
		</ol> -->

		<!-- Wrapper for slides -->
		<div class="carousel-inner animation-container">
			<div class="item slide-1 active">


				<div class="container" style="z-index:20">
					<div class="row">
						<div class="carousel-caption col-md-5 col-sm-12 col-xs-12">
							<h1>DASH EASY</h1>
							<img src="images/content/newSlider-1.png" class="img-responsive slider-images hidden-md hidden-lg" alt="slider 1">
							<h3 class="visible-md visible-xs visible-sm">Dash Easy is the first solution of its kind in Singapore that allows you to pay friends and <br> businesses directly from your mobile phones.<br> Plus, earn attractive interest rates with a linked Dash Easy Savings Account.</h3>
							<h3 class="hidden-md hidden-xs hidden-sm">Dash Easy is the first solution of its kind in Singapore that allows you to pay friends and businesses directly from your mobile phones. Plus, earn attractive interest rates with a linked Dash Easy Savings Account.</h3>

							<h3>Sign up and get your free $5 welcome bonus now!</h3>

							<!-- <p>Download Dash now and get $5 free instantly.</p> -->

							<a href="https://apply.dash.com.sg/easy2/" target="_blank"><button class="cta-btn-3 apply-now">APPLY NOW</button></a>

							<a href="#home-video" class="watch"><button class="watch-video">Watch Video</button></a>
					  	</div> 
					  	<div class="col-md-7 hidden-xs hidden-sm">
					 		<img src="images/content/newSlider-1.png" class="img-responsive" alt="slider 1">
					 	</div>
					  	
				  	</div>
			  	</div>

		  	

			</div>
		</div>
	</div>
</div>
<div style="display:none">
	<div id="home-video">
			<!-- http://www.youtube.com/embed/l-bTlb13RUU?autoplay=1 -->
		<!-- <iframe width="534" height="338" src="http://www.youtube.com/v/l-bTlb13RUU?loop=1" frameborder="0" allowfullscreen></iframe> -->
		<!-- <iframe id="player" type="text/html" width="534" height="338" src="http://www.youtube.com/embed/l-bTlb13RUU?enablejsapi=1&loop=1" frameborder="0" allowfullscreen></iframe> -->
		<div id="player"></div>
	</div>
</div>