<div id="slider-wrapper">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			<li data-target="#carousel-example-generic" data-slide-to="3"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner animation-container">
			<div class="item slide-1 active">
				<div class="img hidden-xs hidden-sm" style="z-index:10">
		  		<div class="animation-panel">
		  			<div class="animation-animation">
		  				<div class="temp-bg"></div>
		  				<div id="myId_01">
							<!-- <h1>Alternative content</h1>
							<p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p> -->
							<img src="images/content/slider-1.png" class="no-flash-img img-responsive" alt="slider 1">
						</div>

		  			</div>
		  		</div>
		  	</div>

				<div class="container" style="z-index:20">
					<div class="row">
						<div class="carousel-caption col-md-5 col-sm-12 col-xs-12">
							<h1>WHAT IS DASH?</h1>
							<h3 class="hidden-md hidden-xs hidden-sm">Dash lets you pay businesses and friends <br> through your mobile phone. Download Dash <br> from the Apple App Store or Google Play <br> to get $5 free instantly.</h3>

							<h3 class="visible-md visible-xs visible-sm">Dash lets you pay businesses and friends through your mobile phone. Download Dash from the Apple App Store or Google Play to get $5 free instantly.</h3>

							<!-- <p>Download Dash now and get $5 free instantly.</p> -->

							<a href="https://apply.dash.com.sg/easy2/" target="_blank"><button class="cta-btn-2 apply-now">APPLY NOW</button></a>
				  	</div> 
				  	<div class="col-md-7 col-sm-12 col-xs-12">
					 		<img src="images/content/slider-1.png" class="img-responsive visible-xs visible-sm" alt="slider 1">
					 	</div>
				  	
			  	</div>
		  	</div>

		  	

			</div>
			<div class="item slide-2">
				<div class="container">
					<div class="row">
						<div class="carousel-caption col-md-6 col-sm-12 col-xs-12">
							<h1>SHOP WITH DASH</h1>
							<h3 class="hidden-md hidden-xs hidden-sm">Use Dash to pay at your favourite retail stores <br> and eateries. Simply fire up your Dash app <br> on your smartphone to make an instant and secure payment.</h3>
							<h3 class="visible-md visible-xs visible-sm">Use Dash to pay at your favourite retail stores and eateries. Simply fire up your Dash app on your smartphone to make an instant and secure payment.</h3>

							<a href="https://apply.dash.com.sg/easy2/" target="_blank"><button class="cta-btn-2 apply-now">APPLY NOW</button></a>
					  </div> 
				  	<div class="col-md-7 col-sm-12 col-xs-12">
					 		<img src="images/content/slider-2.png" class="img-responsive visible-xs visible-sm" alt="slider 2">
					 	</div>					  	
			  	</div>
		  	</div>

		  	<div class="img hidden-xs hidden-sm">
		  		<div class="animation-panel">
		  			<div class="animation-animation">
		  				<div class="temp-bg"></div>


		  				<div id="myId_02">
		  					<img src="images/content/slider-2.png" class="no-flash-img img-responsive" alt="slider 2">
							<!-- <h1>Alternative content</h1>
							<p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p> -->
						</div>


		  			</div>
		  		</div>
		  	</div>

			</div>
			<div class="item slide-3">
				<div class="container">
					<div class="row">
						<div class="carousel-caption col-md-5 col-sm-12 col-xs-12">
							<h1>PAY FRIENDS THROUGH DASH</h1>
							<h3 class="hidden-md hidden-xs hidden-sm">Owe your friend cash from lunch? <br> Don’t bother with withdrawing cash at the ATMs. <br>Transfer the amount to your friend’s mobile number in just one swipe with the Dash app.</h3>
							<h3 class="visible-md visible-xs visible-sm">Owe your friend cash from lunch? Don’t bother with withdrawing cash at the ATMs. Transfer the amount to your friend’s mobile number in just one swipe with the Dash app.</h3>

							<a href="https://apply.dash.com.sg/easy2/" target="_blank"><button class="cta-btn-2 apply-now">APPLY NOW</button></a>
				  	</div> 
				  	<div class="col-md-7 col-sm-12 col-xs-12">
				 		<img src="images/content/slider-3.png" class="img-responsive visible-xs visible-sm" alt="slider 3">
				 	</div>					  	
			  	</div>
		  	</div>

		  	<div class="img hidden-xs hidden-sm">
		  		<div class="animation-panel">
		  			<div class="animation-animation">
		  				<div class="temp-bg"></div>


		  				<div id="myId_03">
		  					<img src="images/content/slider-3.png" class="no-flash-img img-responsive" alt="slider 3">
							<!-- <h1>Alternative content</h1>
							<p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p> -->
						</div>


		  			</div>
		  		</div>
		  	</div>

			</div>
			<div class="item slide-4">
				<div class="container">
					<div class="row">
						<div class="carousel-caption col-md-5 col-sm-12 col-xs-12">
							<h1>DASH EASY</h1>
							<h3 class="hidden-md hidden-xs hidden-sm">Dash Easy is a mobile cash account offered <br> by SingTel linked seamlessly to a savings account <br> offered by Standard Chartered Bank (Singapore) Limited.</h3>
							<h3 class="visible-md visible-xs visible-sm">Dash Easy is a mobile cash account offered by SingTel linked seamlessly to a savings account offered by Standard Chartered Bank (Singapore) Limited.</h3>

							<ul>
								<li><i class="fa fa-chevron-right"></i><span>Apply now and login to your Dash app to immediately find a free $5 welcome bonus.</span></li>
								<!-- <li><i class="fa fa-chevron-right"></i><span>Top up Dash so you can perform your daily transactions (e.g. making payments at shops)</span></li> -->
								<!-- <li><i class="fa fa-chevron-right"></i><span>Receive a FitBit Flex, worth $XXXX</span></li> -->
							</ul>

							<a href="https://apply.dash.com.sg/easy2/" target="_blank"><button class="cta-btn-2 apply-now">APPLY NOW</button></a>
				  	</div> 
				  	<div class="col-md-7 col-sm-12 col-xs-12">
					 		<img src="images/content/slider-4.png" class="img-responsive visible-xs visible-sm" alt="slider 4">
					 	</div>					  	
			  	</div>
		  	</div>

		  	<div class="img hidden-xs hidden-sm">
		  		<div class="animation-panel">
		  			<div class="animation-animation">
		  				<div class="temp-bg"></div>


		  				<div id="myId_04">
		  					<img src="images/content/slider-4.png" class="no-flash-img img-responsive" alt="slider 4">
							<!-- <h1>Alternative content</h1>
							<p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p> -->
						</div>


		  			</div>
		  		</div>
		  	</div>

			</div>
		</div>
	</div>
</div>
